Удалил папку Архив
kompotik/ko2 pull request #13
Opened 2017-05-19 14:50 UTC by KonstantinZv

2017-05-19 15:20 UTC, sotnikov-link requested changes
🤣 Файлы из папки «Архив» не удалил, а переместил в папку «archive». Смотри, что у тебя в ветке: https://github.com/kompotik/ko2/tree/kostya

2017-05-20 08:05 UTC, sotnikov-link requested changes
Нужно сделать, как у Светы:
- визуальные тесты,
- мок-ап.

https://github.com/kompotik/sv2

2017-05-22 11:24 UTC, sotnikov-link requested changes
При добавлении текста в первые два блока, картинки уходят от верха. В остальном, всё хорошо.

<img width="539" alt="2017-05-22 13 18 42" src="https://cloud.githubusercontent.com/assets/10273334/26305981/3d427962-3efa-11e7-9361-059aeee051e3.png">

2017-05-26 08:38 UTC, KonstantinZv commented
Исправил.

2017-05-26 15:55 UTC, sotnikov-link commented
Мёрдж 😃

2017-05-26 15:55 UTC, sotnikov-link approved these changes
Мёрдж 😃

2017-05-26 15:55 UTC, merged